.DEF	cycles		= r5
.DEF	t1 		= r16
.DEF	t2 		= r17
.DEF	t3 		= r18
.DEF	timer_secs	= r19

.EQU	ROAD_R_LED = PB0
.EQU	ROAD_Y_LED = PB1
.EQU	ROAD_G_LED = PB2

.EQU	WALK_R_LED = PB3
.EQU	WALK_G_LED = PB4

.EQU	LED_DIR  = DDRB
.EQU	LED_PORT = PORTB

.EQU	MAX_CYCLES = 2
.EQU	TIMER1_PRESCALE_MASK = 0x0f ; 16384